name: "" # Unique name for data ingestion
environment: "" # Environment identifier
pipeline: "" # Pipeline name must match a directory in the the provided template folder (ie incremental-with-kudu, kudu-table-ddl, truncate-reload)
source:
  url: "" # JDBC Connection url
  username: "" # JDBC Username
  passwordFile: "" # HDFS location of password file
  schema: "" # JDBC Schema / database name
  tableTypes: # Controls the types of tables included in the configuration output
    - table
    - view
# OPTIONAL: table whitelisting
#  tables:
#    - name: table1
#    - name: table2
destination:
  impalaShellCommand: "" # Impala shell command copied from CM
  stagingDatabase:
    name: "" # Staging database
    path: "" # Staging database hdfs path
  reportingDatabase:
    name: "" # Reporting database name (these can be the same as staging database if template allows)
    path: "" # Reporting database path (these can be the same as staging database if template allows)