SELECT
    COLUMNS.TABLE_NAME AS TABLE_NAME,
    COLUMNS.COLUMN_NAME AS COLUMN_NAME,
    COLUMNS.DATA_TYPE AS TYPE_NAME,
    DECODE (COLUMNS.DATA_PRECISION, NULL, DECODE(COLUMNS.DATA_TYPE, 'NUMBER', DECODE(COLUMNS.DATA_SCALE, NULL, 0 , 38), DECODE (COLUMNS.DATA_TYPE, 'CHAR', COLUMNS.CHAR_LENGTH, 'VARCHAR', COLUMNS.CHAR_LENGTH, 'VARCHAR2', COLUMNS.CHAR_LENGTH, 'NVARCHAR2', COLUMNS.CHAR_LENGTH, 'NCHAR', COLUMNS.CHAR_LENGTH, 'NUMBER', 0, COLUMNS.DATA_LENGTH) ), COLUMNS.DATA_PRECISION)
        AS COLUMN_SIZE,
    DECODE (COLUMNS.DATA_TYPE, 'NUMBER', DECODE(COLUMNS.DATA_PRECISION, NULL, DECODE(COLUMNS.DATA_SCALE, NULL, -127 , COLUMNS.DATA_SCALE), COLUMNS.DATA_SCALE), COLUMNS.DATA_SCALE)
        AS DECIMAL_DIGITS,
    DECODE (COLUMNS.NULLABLE, 'N', 0, 1) AS NULLABLE,
    REMARKS.COMMENTS AS REMARKS,
    COLUMNS.DATA_DEFAULT AS COLUMN_DEF,
    COLUMNS.COLUMN_ID AS ORDINAL_POSITION,
    DECODE (COLUMNS.NULLABLE, 'N', 'NO', 'YES') AS IS_NULLABLE,
    COLUMNS.VIRTUAL_COLUMN AS IS_GENERATEDCOLUMN
FROM
    ALL_TAB_COLS COLUMNS
        LEFT OUTER JOIN ALL_COL_COMMENTS REMARKS
                        ON
                                    COLUMNS.OWNER = REMARKS.OWNER
                                AND COLUMNS.TABLE_NAME = REMARKS.TABLE_NAME
                                AND COLUMNS.COLUMN_NAME = REMARKS.COLUMN_NAME
WHERE
        COLUMNS.OWNER NOT IN
        ('ANONYMOUS', 'APEX_PUBLIC_USER', 'APPQOSSYS', 'BI', 'CTXSYS', 'DBSNMP', 'DIP',
         'EXFSYS', 'FLOWS_30000', 'FLOWS_FILES', 'GSMADMIN_INTERNAL', 'IX', 'LBACSYS',
         'MDDATA', 'MDSYS', 'MGMT_VIEW', 'OE', 'OLAPSYS', 'ORACLE_OCM',
         'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'OWBSYS', 'PM', 'SCOTT', 'SH',
         'SI_INFORMTN_SCHEMA', 'SPATIAL_CSW_ADMIN_USR', 'SPATIAL_WFS_ADMIN_USR',
         'SYS', 'SYSMAN', 'SYSTEM', 'TSMSYS', 'WKPROXY', 'WKSYS', 'WK_TEST',
         'WMSYS', 'XDB', 'XS$NULL', 'RDSADMIN')
  AND NOT REGEXP_LIKE(COLUMNS.OWNER, '^APEX_[0-9]{6}$')
  AND NOT REGEXP_LIKE(COLUMNS.OWNER, '^FLOWS_[0-9]{5,6}$')
  AND COLUMNS.OWNER = '{{SCHEMA_NAME}}'
  AND COLUMNS.TABLE_NAME NOT LIKE 'BIN$%'
  AND NOT REGEXP_LIKE(COLUMNS.TABLE_NAME, '^(SYS_IOT|MDOS|MDRS|MDRT|MDOT|MDXT)_.*$')
  AND COLUMNS.HIDDEN_COLUMN = 'NO'
  AND ABS(MOD(ORA_HASH(COLUMNS.COLUMN_NAME), 4)) = {{THREAD_INDEX}}
ORDER BY
    TABLE_NAME,
    COLUMN_NAME,
    ORDINAL_POSITION
