SELECT /*+ PARALLEL(AUTO) */
    INDEXES.TABLE_NAME as TABLE_NAME,
    INDEX_COLUMNS.COLUMN_NAME as COLUMN_NAME
FROM
    ALL_INDEXES INDEXES
        INNER JOIN ALL_IND_COLUMNS INDEX_COLUMNS
                   ON
                               INDEXES.INDEX_NAME = INDEX_COLUMNS.INDEX_NAME
                           AND INDEXES.TABLE_OWNER = INDEX_COLUMNS.TABLE_OWNER
                           AND INDEXES.TABLE_NAME = INDEX_COLUMNS.TABLE_NAME
                           AND INDEXES.OWNER = INDEX_COLUMNS.INDEX_OWNER
WHERE
        INDEXES.OWNER NOT IN
        ('ANONYMOUS', 'APEX_PUBLIC_USER', 'APPQOSSYS', 'BI', 'CTXSYS', 'DBSNMP', 'DIP',
         'EXFSYS', 'FLOWS_30000', 'FLOWS_FILES', 'GSMADMIN_INTERNAL', 'IX', 'LBACSYS',
         'MDDATA', 'MDSYS', 'MGMT_VIEW', 'OE', 'OLAPSYS', 'ORACLE_OCM',
         'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'OWBSYS', 'PM', 'SCOTT', 'SH',
         'SI_INFORMTN_SCHEMA', 'SPATIAL_CSW_ADMIN_USR', 'SPATIAL_WFS_ADMIN_USR',
         'SYS', 'SYSMAN', 'SYSTEM', 'TSMSYS', 'WKPROXY', 'WKSYS', 'WK_TEST',
         'WMSYS', 'XDB', 'XS$NULL', 'RDSADMIN')
  AND NOT REGEXP_LIKE(INDEXES.OWNER, '^APEX_[0-9]{6}$')
  AND NOT REGEXP_LIKE(INDEXES.OWNER, '^FLOWS_[0-9]{5,6}$')
  AND INDEXES.OWNER = '{{SCHEMA_NAME}}'
  AND INDEXES.TABLE_NAME NOT LIKE 'BIN$%'
  {{TABLE_FILTER}}
  AND NOT REGEXP_LIKE(INDEXES.TABLE_NAME, '^(SYS_IOT|MDOS|MDRS|MDRT|MDOT|MDXT)_.*$')
  AND INDEXES.UNIQUENESS = 'UNIQUE'
  AND ABS(MOD(ORA_HASH(INDEX_COLUMNS.COLUMN_NAME), 4)) = {{THREAD_INDEX}}
ORDER BY
    TABLE_NAME
