#import(io.phdata.streamliner.schemadefiner.model.Snowflake)
<%@ val configurationDiff: io.phdata.streamliner.schemadefiner.model.ConfigurationDiff %>
#{
    val destination = configurationDiff.currentDestination.asInstanceOf[Snowflake]
}#
snowsql-cmd=${destination.snowSqlCommand} -f

evolve-schema: evolve-schema.sql
    $(snowsql-cmd) evolve-schema.sql

copy-into: copy-into.sql
    $(snowsql-cmd) copy-into.sql

run:
    $(MAKE) evolve-schema
    $(MAKE) copy-into



