version: '2'

services:
  mysql:
    image: genschsa/mysql-employees
    ports:
      - 3306:3306
    hostname: mysql
    mem_limit: 512M
    environment:
      MYSQL_ROOT_USER: streamliner
      MYSQL_ROOT_PASSWORD: streamliner
      MYSQL_PASSWORD: streamliner

  kimpala:
    image: amfoerster/hadoop-docker
    volumes:
      - "./:/mount"
    hostname: hadoop
    mem_limit: 5G
    environment:
      - PATH=${PATH}:/mount/streamliner/bin
    ports:
      - 7051:7051
      - 7050:7050
      - 8051:8051
      - 8050:8050
      - 8080:8080
      - 50010:50010
      - 50020:50020
      - 50070:50070
      - 50075:50075
      - 21000:21000
      - 21050:21050
      - 22000:22000
      - 23000:23000
      - 23020:23020
      - 8030:8030
      - 8031:8031
      - 8032:8032
      - 8033:8033
      - 8088:8088