name: Streamliner
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11.0.14+101
    - name: Run tests
      run: ./gradlew test
    - name: Run scalafmt
      run: ./gradlew scalafmtCheck
